### PR TITLE
Allow for other actions besides routing

### PR DESCRIPTION
**Pull request by Satyam**
Tabs might be used anywhere within the page and might not always imply routing to a completely different page.  Thus, I made it somewhat more flexible in that sense.

First, the `tabs` argument to the controller didn't seem to fit there.  All the information in that object was related to viewing.  It seemed sensible to move that to the view part of the component.   In doing that, the `overrides` object didn't make sense anymore.

The arguments to the controller part of the component now accept two functions, which can be property getters/setters (usually the same in both).  If none is given, the current default action of routing remains the default.  

The two arguments are:
- A function that returns a `tabName` (such as a property getter) or a string containing the `tabName`. If none given, defaults to `m.routes.param('tab')`
- A function that is called when a tab is clicked.  The function receives the `tabName` of the new tab and the event object that caused the change.  A property setter would take the first of these and ignore the event.  If no argument is given it defaults to `m.route`.

The demo and readme have been changed to reflect these changes.
The demo now shows a second tab that will change tabs every 2 seconds by using a property setter/getter, without affecting the other tab or using routing.

### CODE REVIEW

**Comment by Satyam** [comment]
This is not what I wanted, damned Git!!!!

I meant to do a separate submission, but I am not sure how to do that.  Probably should have made a separate branch, but it is too late now, somehow it got into this same pull request.   Perhaps you can help me untangle this or perhaps you don't mind.  Please help, let me know.

**Comment by Satyam** [comment]
The last commit in this pull request is a datatable.  It is modeled after the one that used to be there in YUI 2.   The data and the definition of the columns is separate.  The data can be fetched from a remote webserver by simply specifying the URL of the server.  It supports sorting by columns and nested headings.

The first question, though, should have been, do you mind putting it along the other components?  I don't want to force you into becoming the librarian but, so far, you've done so.  I don't mean for you to maintain my code, but I am not good at doing GIT, as you might have noticed.

**Comment by eddyystop** [comment]
I think Mithril's success will partially depend on the ecosystem around it. So I've been investing time generalizing components I need and publishing them. I'm happy to include your components as I expect they'll behave similarly to and nicely with the rest.

I'll look tomorrow as that's a holiday here.

I understand you about git. It's teeth-clenching sometimes.

**Comment by eddyystop** [comment]
I will certainly find datatable useful, as I believe others will too. Thanks.
Could you please review the readme I wrote up for it?

datatable-runner passes className and width to .controller(). I don't believe it uses them and perhaps I should remove them.

github wouldn't let me automatically merge your pull requests. I pasted datatable into the repo as I'm not familar with using git with github. I plan to do the same with tabs.

You may want to backup your changed modules, delete your fork and fork it again, so we'll be in sync.

**Comment by eddyystop** [comment]
Hmmm ... I hadn't seen your last changes, 6348af9 onwards. I'll include them shortly.

**Comment by Satyam** [comment]
I've made several updates to the original submission, including a readme file in markdown format and I cleaned up which parameters go where.

I guess you could download the zip file from my fork of your repository and selectively expand the files for my components into your local repo and then commit that.  

It is late in my corner of the world, I'll try to get a new copy tomorrow.

**Comment by eddyystop** [comment]
Zip'ing your fork worked well. Everything is across. Nice examples.

On a related topic, would you mind telling me what you think of /public/occlusion.html? A pain point I have with tables (lists, etc.) is they sometimes are too large for some device. This occlusion container may address the vertical.

I can also see containers that scroll whatever they contain, ones that can be moved, modals, etc.

**Comment by Satyam** [comment]
I now have my local repository in sync with yours.   

I like the occlusion control, though its name is somehow cryptic, at least to me.

I noticed in the description of the [controller](https://github.com/eddyystop/mithril-components/tree/master/components/occlusionContainer#controller) it lists `contentsController` twice, the second time should be `contentsView`.

I like the idea and I'd love to put it into DataTable though is not so easy as the headers have to remain in place while the body scrolls and the vertical dividers have to match.   Pagination is easier to do and I was planing on doing that shortly.

There are not many scrollable things other than a list I can think of.  Thus, I am wondering whether it might be easier to have a, say,  `scrollingList` or `infiniteScrollingList` component so that the developer doesn't need to implement the list part of it.

With that in mind, I think I would provide the controller of the component with an `itemProvider`  function that would produce the items to be displayed as they are requested, and another function (possibly a property getter/setter) that returns the length of the list.

The component would initially request, say, the first 10 items (this can be configured) and calculate the height of the items based on the actual height of those 10 items.   It would immediately do a second request if those initial 10 items don't get to fill in the container height. 

I don't like giving the item height via code as a later change in the CSS might mess things up.  Checking how tall they actually are seems safer.   Even the end user might have his/her browser configured with a larger font and the items in the list would look cramped in a fixed-size container.  I remember a finance guy in a company I worked for that had what in those days was a huge screen to have his enormous spreadsheets, and he used a very small font to make it all fit in.  He would have hated to see the items take up so much waster space.

The component should check the length of the list regularly as the length might well be an estimate (like google's search, the number of 'oooo's in the colorful Gooooooogle' at the bottom of the page is  just an estimate).   The developer might load batches of items from the server and the size and position of the scroll bar index would change accordingly.

A falsy (null, undefined or 0) length would mean the list might go forever.

I'd like to suggest to open new issues instead of keep adding to this item, where the conversation would get lost and others might skip on it for lack of a decent title.   So, I'll just close it.

**Pull request closed without merging**
